### ISSUE TITLE
用户能看到的设备问题

### ISSUE THREAD

**Issue by AnyISalIn** [fly-over-shanghai/njupt_3s#1]
`thingsboard` 里面，`TENANT_ADMIN` 创建设备后将与 `CUSTOMER` 关联，这个 `CUSTOMER` 下的所有 `CUSTOMER_USER` 都能看到这个设备的信息

目前注册用户和设备都是加到 `CUSTOMER A` 中，所以所有的用户都能看到所有设备，和我们想要的效果不一致。

建议改成以下形式:

1. 每个 `CUSTOMER` 中只有一个 `CUSTOMER`，即创建用户时同时创建一个与之对应的 `CUSTOMER`，并将用户加入到里面
2. 用户创建的设备，加入到他自己的 `CUSTOMER` 中

**Comment by yanyao** [comment]
@AnyISalIn 能否把创建customer的API找一下，并且列出来使用方法

**Comment by AnyISalIn** [comment]
@yanyao swagger-ui 里面的 customer-controller 里面有，主要是 @wayne62 这边后端的一系列逻辑

**Comment by wayne62** [comment]
预计本周会继续调试api

**Comment by yanyao** [comment]
这个问题修复了吧？
